language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install -g gulp

#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "ZQ-jhon"
  - git config user.email "350037310@qq.com"
  - git add .
  - git commit -m "Update docs with TRAVIS-CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/ZQ-jhon/ZQ-jhon.github.io.git
             