language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - npm run ups

after_script:
  - cd ./public
  - git init
  - git config user.name "ZQ-jhon"
  - git config user.email "350037310@qq.com"
  - git add .
  - git commit -m "Update docs from TRAVIS-CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo --{Hexo源码分支名称}
env:
 global:
   - GH_REF: github.com/dmego/dmego.github.io.git --{仓库地址}