pool:
  vmImage: 'ubuntu-16.04'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  name: 'building'
- script: npm install
- script: npx hexo g
  name: 'push'
- pwsh: |
    cd ./public
    cp ../Dockerfile Dockerfile
    cp ../nginx.conf nginx.conf
    cp ../scripts scripts
    cp ../.gitignore .gitignore
    git init
    git config user.name "ZQ-jhon"
    git config user.email "350037310@qq.com"
    git add .
    git commit -m "🤖 Update Docs with auzre-pipeline bot @ $(Get-Date -Format 'yyyy-MM-dd hh:mm:ss')"
    git push --force --quiet "https://$(Azure_PAT)@github.com/ZQ-jhon/ZQ-jhon.github.io.git" master:master
