pool:
  vmImage: 'ubuntu-16.04'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  name: 'building'
- script: ls -ls
- script: npm install
- script: npx hexo g
  name: 'initChildRepo'
- script: cd ./public
- script: ls
- script: sudo cp ../Dockerfile Dockerfile
- script: sudo cp ../nginx.conf nginx.conf
- script: git init
- script: git config user.name "ZQ-jhon"
- script: git config user.email "350037310@qq.com"
- script: git add .
  name: 'commitAndPush'
- script: git commit -m "Update Docs with auzre-pipeline"
- script: git push --force --quiet "https://${secret.GH_TOKEN}@github.com/ZQ-jhon/ZQ-jhon.github.io.git" master:master