pool:
  vmImage: 'ubuntu-16.04'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  name: 'building'
- script: npm install
- script: npx hexo g
  name: 'initChildRepo'
- script: |
    cd ./public
    cp ../Dockerfile Dockerfile
    cp ../nginx.conf nginx.conf
    git init
    git config user.name "ZQ-jhon"
    git config user.email "350037310@qq.com"
    git add .
    git commit -m "Update Docs with auzre-pipeline"
    git push --force --quiet "https://${secret.GH_TOKEN}@github.com/ZQ-jhon/ZQ-jhon.github.io.git" master:master
  name: 'commitAndPush'